name: ci
on: [pull_request]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version: 14.x
      
      - name: Install dependencies
        uses: yarn install

      - name: Linting
        uses: yarn lint
      
      - name: Test
        uses: yarn test
      
      - name: Build
        uses: yarn build
       